app/users/__init__.py
from flask import Blueprint

user_bp = Blueprint("users",
                    __name__,
                    url_prefix="/user",
                    template_folder="templates/users"
                    )

from . import views

app/users/views.py
from . import user_bp
from flask import render_template, request, redirect, url_for, make_response, session, flash
from datetime import timedelta


@user_bp.route('/profile', methods=['GET', 'POST'])
def get_profile():
    if "username" in session:
        username_value = session["username"]
        color_theme = request.cookies.get('color_theme', 'light')
        cookies = request.cookies
        if request.method == 'POST':
            if 'add_cookie' in request.form:
                key = request.form['cookie_key']
                value = request.form['cookie_value']
                duration = request.form.get('cookie_duration', type=int)
                response = make_response(redirect(url_for('users.get_profile')))
                response.set_cookie(key, value, max_age=duration)
                flash(f"Cookie was added successfully!", "success")
                return response

            elif 'delete_cookie' in request.form:
                key = request.form['cookie_key_delete']
                response = make_response(redirect(url_for('users.get_profile')))
                response.set_cookie(key, '', expires=0)
                flash(f"Cookie was deleted successfully!", "success")
                return response

            elif 'delete_all_cookies' in request.form:
                response = make_response(redirect(url_for('users.get_profile')))
                for key in cookies:
                    response.set_cookie(key, '', expires=0)
                flash("All cookies were deleted successfully", "success")
                return response

        return render_template("profile.html", username=username_value, cookies=cookies, color_theme=color_theme)
    else:
        flash("Error: access denied. Please login.", "danger")
        return redirect(url_for("users.login"))


@user_bp.route('/set_color_theme', methods=['POST'])
def set_color_theme():
    color_theme = request.form['color_theme']
    response = make_response(redirect(url_for('users.get_profile')))
    response.set_cookie('color_theme', color_theme, max_age=2592000)
    return response


@user_bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        valid_username = "admin"
        valid_password = "password"

        if username == valid_username and password == valid_password:
            session["username"] = username
            flash("Success: session added successfully.", "success")
            return redirect(url_for("users.get_profile"))
        else:
            flash("Error: Invalid username or password.", "danger")
            return redirect(url_for("users.login"))
    return render_template("login.html")


@user_bp.route('/logout')
def logout():
    # Видалення користувача із сесії
    session.pop('username', None)
    flash("You have successfully logged out.", "info")
    return redirect(url_for("users.login"))


@user_bp.route('/hi/<string:name>')  # /hi/ivan?age=30
def greetings(name):
    name = name.upper()
    age = request.args.get("age", None, int)
    return render_template("hi.html", name=name, age=age)


@user_bp.route("/admin")
def admin():
    to_url = url_for("users.greetings", name="administrator", age=45,
                     _external=True)  # "http://localhost:8080/hi/administrator?age=45"
    print(to_url)
    return redirect(to_url)


@user_bp.route('/set_cookie')
def set_cookie():
    response = make_response('Кука встановлена')
    response.set_cookie('username', 'student', max_age=timedelta(seconds=60))
    return response


@user_bp.route('/get_cookie')
def get_cookie():
    username = request.cookies.get('username')
    return f'Користувач: {username}'


@user_bp.route('/delete_cookie')
def delete_cookie():
    response = make_response('Кука видалена')
    response.set_cookie('username', '', expires=0)  # response.set_cookie('username', '', max_age=0)
    return response

app/users/templates/users/hi.html
{% extends 'base.html' %}

{% block title %} Greeting Page {% endblock %}

{% block content %}


<nav class="nav_greet greet_links p-2 pb-1">
    <ul>
        <li>
            <a href="{{ url_for('users.greetings', name='John', age=30) }}">Greet John</a>
        </li>
        <li>
            <a href="{{ url_for('users.admin') }}">Admin</a>
        </li>
    </ul>
</nav>


<div class="card p-3 hover_shadow mb-5 mt-4">
    <div class="card-body">
        <h2>Hello, {{ name }}!</h2>
        {% if age %}
        <h4 class="provided">You are: {{ age }} years old.</h4>
        {% else %}
        <h4 class="not_provided">Age is unknown</h4>
        {% endif %}
    </div>
</div>

{% endblock %}

app/users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Login Page{% endblock %}

{% block content %}

<div class="container mt-5 ">
    <h2 class="text-center">Login</h2>
    <form action="{{ url_for('users.login') }}" method="post" class="mt-4 mb-5 login_form">
        <div class="form-group mb-3">
            <label for="username">Ім'я користувача:</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Введіть ім'я користувача" required>
        </div>
        <div class="form-group mb-3">
            <label for="password">Пароль:</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Введіть пароль" required>
        </div>
        <button type="submit" class="btn btn-dark w-100">Увійти</button>
    </form>
</div>

{% endblock %}

app/users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Greeting Page{% endblock %}

{% block content %}

<body class="{% if color_theme == 'dark' %}bg-dark text-light{% else %}bg-light text-dark{% endif %}">
<div class="mt-5 d-grid gap-2 d-md-flex justify-content-md-end">
    <form method="post" action="{{ url_for('users.set_color_theme') }}">
        <label><strong>Вибрати тему:</strong></label>
        <button type="submit" name="color_theme" value="light" class="btn btn-light">Light mode</button>
        <button type="submit" name="color_theme" value="dark" class="btn btn-dark">Dark mode</button>
    </form>
</div>

<div class="container mt-5">
    <div class="mt-3 profile">
        <h1>Вітаю, {{ username }}! </h1>
        <h2>Ви успішно увійшли в профіль.</h2>
    </div>
    <div class="mt-4">
        <a href="{{ url_for('users.logout') }}" class="btn btn-warning mt-3 mb-5">Logout</a>
    </div>
</div>


<hr>
<h1 class="text-center">Робота з Cookie</h1>
<hr>


<div class="mt-5">
    <h3>Додати кукі:</h3>
    <form method="post" action="{{ url_for('users.get_profile') }}">
        <input type="hidden" name="add_cookie">
        <div class="row">
            <div class="col-md-3">
                <label for="cookie_key">Ключ:</label>
                <input type="text" class="form-control" id="cookie_key" name="cookie_key" required>
            </div>
            <div class="col-md-3">
                <label for="cookie_value">Значення:</label>
                <input type="text" class="form-control" id="cookie_value" name="cookie_value" required>
            </div>
            <div class="col-md-3">
                <label for="cookie_duration">Термін дії (сек):</label>
                <input type="number" class="form-control" id="cookie_duration" name="cookie_duration" min="1"
                       required>
            </div>
        </div>
        <button type="submit" class="btn btn-success mt-3">Додати</button>
    </form>
</div>


<div class="mt-5">
    <h3>Видалити кукі за ключем:</h3>
    <form method="post" action="{{ url_for('users.get_profile') }}">
        <input type="hidden" name="delete_cookie">
        <div class="col-md-3">
            <input type="text" class="form-control" id="cookie_key_delete" name="cookie_key_delete" required>
        </div>
        <button type="submit" class="btn btn-warning mt-2">Видалити</button>
    </form>
</div>

<div class="mt-5">
    <h3>Видалити всі кукі:</h3>
    <form method="post" action="{{ url_for('users.get_profile') }}">
        <input type="hidden" name="delete_all_cookies">
        <button type="submit" class="btn btn-danger mt-2">Видалити</button>
    </form>
</div>

<div class="mt-5 mb-5 section">
    <h3>Список всіх кукі:</h3>
    {% if cookies %}
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Ключ</th>
            <th>Значення</th>
        </tr>
        </thead>
        <tbody>
        {% for key, value in cookies.items() %}
        <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3>Немає Cookie</h3>
    {% endif %}
</div>
</body>
{% endblock %}