app/posts/__init__.py
from flask import Blueprint

post_bp = Blueprint("posts",
                    __name__,
                    url_prefix="/post",
                    template_folder="templates/posts"
                    )

from . import views

app/posts/views.py
from . import post_bp
from flask import render_template, abort

posts = [
    {"id": 1, 'title': 'My First Post', 'content': 'This is the content of my first post.', 'author': 'John Doe'},
    {"id": 2, 'title': 'Another Day', 'content': 'Today I learned about Flask macros.', 'author': 'Jane Smith'},
    {"id": 3, 'title': 'Flask and Jinja2', 'content': 'Jinja2 is powerful for templating.', 'author': 'Mike Lee'}
]


@post_bp.route('/')
def get_posts():
    return render_template("posts.html", posts=posts)


@post_bp.route('/<int:id>')
def detail_post(id):
    if id > 3:
        abort(404)
    post = posts[id - 1]
    return render_template("detail_post.html", post=post)

app/posts/templates/posts/detail_post.html
{% extends 'base.html' %}

{% block title %} POSTS {% endblock %}

{% block content %}

    <h1>Post № {{post["id"]}} - {{post["title"]}} </h1>

    <p>{{ post.get('content') }}</p>

    <a href="{{ url_for('posts.get_posts')}}">Return posts</a>

{% endblock %}

app/posts/templates/posts/posts.html
{% extends 'base.html' %}

{% block title %} POSTS {% endblock %}

{% block content %}

<h1>Articles</h1>

<ul>
    {% for post in posts%}
        <li> {{post["id"]}} -
             <a href="{{ url_for('posts.detail_post', id=post['id']) }}">{{post["title"]}}</a>
        </li>
    {% endfor %}
</ul>

{% endblock %}